### ISSUE TITLE
train_loss

### ISSUE THREAD

**Issue by Arbor334** [rui-ye/OpenFedLLM#13]
![image](https://github.com/rui-ye/OpenFedLLM/assets/57646922/a75d10a8-7c5d-4c4b-b060-1e08a3007701)
Hello, is this train_loss so high?

**Comment by rui-ye** [comment]
Hello, could you please show more details of your current experimental setting?

**Comment by Arbor334** [comment]
![Uploading image.png…]()
Your conda environment used, A100-80GB  
I ran for eight hours today

**Comment by Arbor334** [comment]
i just run `bash run_stf.sh`  and  the  result  look like  the up photo

**Comment by Arbor334** [comment]
hi,bro

**Comment by rui-ye** [comment]
ic. This experimental setting is the same as that in our paper. This high loss value could be not a big issue and I suppose the resulting model would work if everything goes well. You can test it by inferring on benchmarks such as MT-Bench and check the responses.

(The reason of the relatively high loss could be that federated training is less stable than centralized training and that we apply a relatively small batch size)

**Comment by lylaiyy** [comment]
@Arbor334 I also meet this question. Do you konw the reason of this question now?
