### ISSUE TITLE
Evaluation on other datasets?

### ISSUE THREAD

**Issue by 1xbq1** [rui-ye/OpenFedLLM#14]
Hello and thank you for your great work. In addition to MT-Bench, Vicuna benchmark, and Advbench, do you have test details or codes for the other datasets?

**Comment by rui-ye** [comment]
Yes. We are working on that and sorry for the delay. Please let me know what benchmarks are you interested right now so that we can release those first.

**Comment by 1xbq1** [comment]
Thank you very much, and I hope to publish benchmarks in specific domains like FinGPT, MedAlpaca, and Code-Alpaca first, thanks again.
