### ISSUE TITLE
Results of training on Alpaca-GPT4 and testing on MT-Bench

### ISSUE THREAD

**Issue by 1xbq1** [rui-ye/OpenFedLLM#15]
Hello, directly run your code, the configuration has not changed, the test steps are also according to your evaluation/open_ended process, but gen_judge_mtbench.py results are all ERROR. What's the problem? Looking forward to your reply.

Run the following command:
1. sh training_scripts/run_sft.sh
2. python utils/merge_lora.py --base_model_path "meta-llama/Llama-2-7b-hf" --lora_path "output/alpaca-gpt4_20000_fedavg_c20s2_i10_b16a1_l512_r32a64_20240313104822/checkpoint-200"
3. CUDA_VISIBLE_DEVICES=2 python gen_model_answer_mt.py --base_model_path "../../output/alpaca-gpt4_20000_fedavg_c20s2_i10_b16a1_l512_r32a64_20240313104822/full-200" --template "alpaca"
4. python gen_judge_mtbench.py --judge_model gpt-4-1106-preview --model_list alpaca-gpt4_20000_fedavg_c20s2_i10_b16a1_l512_r32a64_20240313104822_200
5. python show_results_mt.py --model_list alpaca-gpt4_20000_fedavg_c20s2_i10_b16a1_l512_r32a64_20240313104822_200 --judge_model gpt-4-1106-preview

Here are the results of running on the A40:
[model_answer.zip](https://github.com/rui-ye/OpenFedLLM/files/14610790/model_answer.zip)
[model_judgment.zip](https://github.com/rui-ye/OpenFedLLM/files/14610791/model_judgment.zip)

**Comment by rui-ye** [comment]
Hi, are you using the latest code?

**Comment by rui-ye** [comment]
I think that this might has been addressed by https://github.com/rui-ye/OpenFedLLM/commit/4e9a949315138e056bc1688392a24d06976d3b1e. Please check the modification in show_results_mt.py.

**Comment by 1xbq1** [comment]
> Hi, are you using the latest code?

Yes, the above results are from running the latest code, where line 32 of show_results_mt.py is "mtbench".

**Comment by rui-ye** [comment]
emmm. We did not come across such error before. Could you please provide your screen shot during running gen_judge_mtbench.py?

**Comment by 1xbq1** [comment]
![screen_1](https://github.com/rui-ye/OpenFedLLM/assets/105406464/522c75a5-5648-4a4d-b28f-5f4b9edf2c1f)
![Screen_2](https://github.com/rui-ye/OpenFedLLM/assets/105406464/98f6b396-8f05-4a2d-a6bb-8244e2bbe171)

**Comment by rui-ye** [comment]
oh, this is related to the issue of network connection between your working device and OpenAI, but not related to the code.

**Comment by 1xbq1** [comment]
May I ask if there is a network connection error, will it affect the judgment result of gpt-4 api? Ok, thank you for your reply.

**Comment by 1xbq1** [comment]
> May I ask if there is a network connection error, will it affect the judgment result of gpt-4 api? Ok, thank you for your reply.

Because I see that the progress bar is increasing in the back.

**Comment by rui-ye** [comment]
This error indicates that your device fails to connect gpt-4 api, therefore, no judgement is received. Please make sure your network connection is well and you will see the judgment of gpt-4 printed on the screen.

The following is an example:

> The AI assistant's response is a well-structured and engaging travel blog post about a trip to Hawaii. It effectively highlights cultural experiences, such as participating in a hula lesson and trying traditional Hawaiian food, and must-see attractions like Haleakala National Park and Hanauma Bay. The post is informative, providing insights into Hawaiian heritage and the unique biodiversity of the islands. The language used is descriptive and evocative, painting a vivid picture of the experiences and scenery.\n\nThe response is relevant to the user's request, focusing on cultural aspects and notable attractions. It is accurate in its descriptions of Hawaiian culture and the natural beauty of the islands. The depth of the post is appropriate for a blog entry, offering personal insights and recommendations without overwhelming the reader with excessive detail. Creativity is shown in the way the assistant weaves together personal experiences with factual information to create a narrative that is both informative and personal. The level of detail is sufficient to engage the reader and provide a sense of what a trip to Hawaii might entail.\n\nOverall, the response is a strong example of a travel blog post that would likely be helpful and enjoyable for someone interested in visiting Hawaii. It meets the criteria of helpfulness, relevance, accuracy, depth, creativity, and level of detail.\n\nRating: [[8]]

**Comment by 1xbq1** [comment]
Ok, I see. Thank you very much for your patient reply.
