### ISSUE TITLE
Continue training according to checkpoint

### ISSUE THREAD

**Issue by bluedale7** [rui-ye/OpenFedLLM#16]
I have generated several checkpoint model folders after 200 rounds of training, can I continue training with this model next time? If so, how to use the trained model parameters.

**Comment by rui-ye** [comment]
Sorry for the late response. We haven't tried this yet but I think that the following steps would work.

1. Add `from peft import PeftModel`
2. Repalcing https://github.com/rui-ye/OpenFedLLM/blob/d45644deda4c0cf9080c0e7dff2fbe7037090d96/main_sft.py#L44 with `model = PeftModel.from_pretrained(model, YOU_LORA_PATH, is_trainable=True)` should work~

You can also refer to the doc of PEFT [here](https://huggingface.co/docs/peft/tutorial/peft_model_config).
