### ISSUE TITLE
How can i perform local training using the OpenFedLLM?

### ISSUE THREAD

**Issue by SuperChanS** [rui-ye/OpenFedLLM#20]
I want to perform the local training without any federated learning operations in the same settings. So how can I modify the parameters in the off-the-shelf code framework?

**Comment by rui-ye** [comment]
Hi. Just assign `fed_alg` as localx will runs the x-th client's local training. For example, fed_alg=local0 runs client 0. You can check the code https://github.com/rui-ye/OpenFedLLM/blob/859865a7c096652a17e6957a57b29c6ed0ca1e60/federated_learning/fed_global.py#L6

**Comment by SuperChanS** [comment]
Additionally, how can i perform the centralized training?

**Comment by rui-ye** [comment]
You can set the `num_clients` as 1 and `fed_alg` as 'local0' or 'fedavg'.
