### ISSUE TITLE
ValueError: Unsupported `fed_alg`: fedadam

### ISSUE THREAD

**Issue by Charleston77** [rui-ye/OpenFedLLM#34]
<img width="335" alt="d8bc29d309dfbc552a06b807e5c9103" src="https://github.com/user-attachments/assets/144013e8-3be3-4bab-9003-3f86b461b030">

Dear author,
Hello! I set fed_alg = "fedadam" in the run_stf.sh, but an error occurs during execution. I'm wondering why. Didn't it say that seven algorithms are supported? I'm earnestly looking forward to your reply. Best regards.

**Comment by rui-ye** [comment]
Sorry for the mistake. We just fixed that; see https://github.com/rui-ye/OpenFedLLM/commit/fc31973558b2d5f49dcda54f98468a270916a04c.
