### ISSUE TITLE
What is the token count required to execute a FedAvg-based SFT script in MTBench

### ISSUE THREAD

**Issue by Charleston77** [rui-ye/OpenFedLLM#36]
Dear Author, I sincerely appreciate your significant contributions to the field of federated learning with large models. One inquiry I have is regarding the apparent high token expenditure required for experimental verification. Do you possess any reference responses from GPT-3.5?

**Comment by rui-ye** [comment]
Sorry. We did not use GPT-3.5 in our experiments so we do not have such responses.
